version: '3.8'
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/src
        ports:
            - 8000:8000
        depends_on:
            - database
    database:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=blog
            - POSTGRES_USER=blog
            - POSTGRES_PASSWORD=blog
            - TZ=GMT
        volumes:
            - $HOME/.volumes-docker/pg/blog:/var/lib/postgresql/data
